#!/usr/bin/env bash
set -e

cd ~/dotfiles
STOW_LOG_FILE="stow.log"
CURRENT_HOST=$(hostname -s)

echo "Running gnu stow"
nix shell nixpkgs#stow -c stow . 2>&1 | tee -a $STOW_LOG_FILE
echo "Formatting nix files"
nix shell nixpkgs#alejandra -c alejandra --quiet **/*.nix
echo "Updating nixvim flake"
nix flake update my-nixvim
echo "Rebuilding nix darwin"
darwin-rebuild switch --flake .#"${CURRENT_HOST}"
