[v1]
"bacon 2.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bacon"]
"code-minimap 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["code-minimap"]
"coreutils 0.0.14 (registry+https://github.com/rust-lang/crates.io-index)" = ["coreutils"]
"licensor 2.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["licensor"]
"lolcat 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["lolcat"]
"onehistory 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["onehistory"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"uwuify 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["uwuify"]
"wthrr 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["wthrr"]
