[v1]
"alacritty 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["alacritty"]
"bacon 2.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bacon"]
"bottom 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"cargo-binutils 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-cov",
    "cargo-nm",
    "cargo-objcopy",
    "cargo-objdump",
    "cargo-profdata",
    "cargo-readobj",
    "cargo-size",
    "cargo-strip",
    "rust-ar",
    "rust-cov",
    "rust-ld",
    "rust-lld",
    "rust-nm",
    "rust-objcopy",
    "rust-objdump",
    "rust-profdata",
    "rust-readobj",
    "rust-size",
    "rust-strip",
]
"code-minimap 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["code-minimap"]
"coreutils 0.0.14 (registry+https://github.com/rust-lang/crates.io-index)" = ["coreutils"]
"licensor 2.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["licensor"]
"lolcat 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["lolcat"]
"onehistory 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["onehistory"]
"ravedude 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["ravedude"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"svdtools 0.2.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["svdtools"]
"trunk 0.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
"uwuify 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["uwuify"]
"wthrr 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["wthrr"]
