[v1]
"alacritty 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["alacritty"]
"bacon 3.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bacon"]
"bottom 0.10.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"cargo-binutils 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-cov",
    "cargo-nm",
    "cargo-objcopy",
    "cargo-objdump",
    "cargo-profdata",
    "cargo-readobj",
    "cargo-size",
    "cargo-strip",
    "rust-ar",
    "rust-cov",
    "rust-ld",
    "rust-lld",
    "rust-nm",
    "rust-objcopy",
    "rust-objdump",
    "rust-profdata",
    "rust-readobj",
    "rust-size",
    "rust-strip",
]
"cargo-generate 0.22.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-generate"]
"cargo-update 16.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"code-minimap 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["code-minimap"]
"coreutils 0.0.29 (registry+https://github.com/rust-lang/crates.io-index)" = ["coreutils"]
"create-tauri-app 4.5.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-create-tauri-app"]
"diesel_cli 2.2.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["diesel"]
"licensor 2.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["licensor"]
"lolcat 1.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lolcat"]
"onehistory 0.3.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["onehistory"]
"ravedude 0.1.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["ravedude"]
"ripgrep 14.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"rustowl 0.2.1 (path+file:///Users/ellie/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustowl-0.2.1/.tmp)" = ["rustowlc"]
"rustowl 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustowl"]
"svdtools 0.4.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["svdtools"]
"tauri-cli 2.2.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tauri"]
"trunk 0.21.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
"uwuify 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["uwuify"]
"wthrr 1.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["wthrr"]
"zoxide 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
