[ids]
*

[main]
capslock = overload(capsescape, esc)

[capsescape]
space = toggle(nav)
h = left
k = up
j = down
l = right

[nav]
space = toggle(nav)
capslock = toggle(nav)
h = left
k = up
j = down
l = right

[colemak:layout]
q = q
w = w
e = f
r = p
t = b
y = j
u = l
i = u
o = y
p = ;
a = a
s = r
d = s
f = t
g = g
h = m
j = n
k = e
l = i
; = o
z = x
x = c
c = d
v = v
b = z
n = k
m = h

[control]
0 = setlayout(main)
9 = setlayout(colemak)
